language: rust
sudo: false
matrix:
  include:
    - rust: 1.11.0
      env:
       - FEATURES='quickcheck'
    - rust: stable
      env:
       - FEATURES='quickcheck'
    - rust: beta
      env:
       - FEATURES='quickcheck'
    - rust: nightly
      env:
       - FEATURES='quickcheck'
       - BENCH=1
branches:
  only:
    - master
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES")
